import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from './supabase';

const MOODS = [
  ['happy','Senang','☀️'],['calm','Tenang','🌿'],['excited','Semangat','✨'],
  ['sad','Sedih','☁️'],['anxious','Cemas','🌫️'],['angry','Marah','⚡']
];
const moodLabel = id => MOODS.find(x=>x[0]===id)?.[1] || id;
const moodEmoji = id => MOODS.find(x=>x[0]===id)?.[2] || '🙂';
const NEGATIVE = new Set(['sad','anxious','angry']);
const css = `
*{box-sizing:border-box}body{margin:0;background:#eef1f7;color:#202334;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,textarea,select{font:inherit}button{cursor:pointer}.app{min-height:100vh;padding:24px}.shell{max-width:1120px;margin:auto;background:#fff;border-radius:24px;box-shadow:0 18px 50px rgba(30,38,70,.12);overflow:hidden}.top{padding:18px 24px;border-bottom:1px solid #e9ebf2;display:flex;align-items:center;justify-content:space-between}.brand{font-weight:800;font-size:20px}.muted{color:#747b91}.content{padding:28px}.grid{display:grid;gap:18px}.two{grid-template-columns:repeat(2,minmax(0,1fr))}.three{grid-template-columns:repeat(3,minmax(0,1fr))}.card{border:1px solid #e5e8f0;border-radius:18px;padding:20px;background:#fff}.soft{background:#f7f8fc}.btn{border:0;border-radius:12px;padding:11px 15px;font-weight:700}.primary{background:#202334;color:#fff}.secondary{background:#eef0f6;color:#30364b}.danger{background:#fff0ef;color:#b33d35}.input{width:100%;border:1px solid #dfe3ec;border-radius:12px;padding:12px;margin-top:6px;background:#fff}.label{font-size:13px;font-weight:700}.nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:22px}.nav button{border:1px solid #e2e5ed;background:#fff;padding:9px 13px;border-radius:999px;font-weight:700}.nav button.active{background:#202334;color:#fff}.moodgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.mood{border:1px solid #e1e5ed;background:#fff;border-radius:15px;padding:14px;text-align:center}.mood.selected{border:2px solid #202334;background:#f3f4f8}.stat{font-size:28px;font-weight:800}.tablewrap{overflow:auto}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:11px 9px;border-bottom:1px solid #eceef4;text-align:left;font-size:13px;vertical-align:top}.pill{display:inline-block;padding:5px 9px;border-radius:999px;background:#eef0f6;font-size:12px;font-weight:700}.alert{padding:12px 14px;border-radius:12px;background:#fff5df;color:#76521c}.error{padding:12px 14px;border-radius:12px;background:#fff0ef;color:#a43d35}.success{padding:12px 14px;border-radius:12px;background:#ecfaf4;color:#247451}.login{max-width:470px;margin:7vh auto}.center{text-align:center}.small{font-size:12px}.actions{display:flex;gap:8px;flex-wrap:wrap}.bar{height:9px;border-radius:99px;background:#edf0f5;overflow:hidden}.bar>i{display:block;height:100%;background:#5b6ee1}.modal{position:fixed;inset:0;background:rgba(25,30,50,.45);display:flex;align-items:center;justify-content:center;padding:20px}.modal .card{max-width:560px;width:100%;max-height:90vh;overflow:auto}@media(max-width:760px){.app{padding:10px}.content{padding:18px}.two,.three{grid-template-columns:1fr}.moodgrid{grid-template-columns:repeat(2,1fr)}}
`;

function csvDownload(rows,name){if(!rows.length)return;const keys=Object.keys(rows[0]);const q=v=>`"${String(v??'').replaceAll('"','""').replace(/\r?\n/g,' ')}"`;const csv='\ufeff'+[keys.map(q).join(','),...rows.map(r=>keys.map(k=>q(r[k])).join(','))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

function Auth({onAuth}){
 const [signup,setSignup]=useState(false),[role,setRole]=useState('student'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setError('');setBusy(true);try{let r;if(signup) r=await supabase.auth.signUp({email,password}); else r=await supabase.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(signup){if(!r.data.user)throw new Error('Akun belum dibuat.');const {error:pe}=await supabase.from('profiles').upsert({id:r.data.user.id,role,full_name:name.trim()||email.split('@')[0]});if(pe)throw pe; if(!r.data.session) {setError('Akun dibuat. Jika verifikasi email aktif, cek email lalu login.');return}}onAuth()}catch(x){setError(x.message||'Terjadi kesalahan.')}finally{setBusy(false)}}
 if(!supabase)return <div className="login card"><h1>EmoTrack AutoBK</h1><div className="error">Supabase belum dikonfigurasi. Isi <b>VITE_SUPABASE_URL</b> dan <b>VITE_SUPABASE_ANON_KEY</b> pada <code>.env.local</code>.</div></div>;
 return <div className="login card"><div className="center"><div style={{fontSize:42}}>🌤️</div><h1>EmoTrack AutoBK</h1><p className="muted">Check-in emosi, jurnal, dan pemantauan Guru BK dalam satu tempat.</p></div><div className="nav"><button className={!signup?'active':''} onClick={()=>setSignup(false)}>Masuk</button><button className={signup?'active':''} onClick={()=>setSignup(true)}>Buat akun</button></div><form onSubmit={submit} className="grid"><div><label className="label">Peran</label><select className="input" value={role} onChange={e=>setRole(e.target.value)}><option value="student">Siswa</option><option value="teacher">Guru BK</option></select></div>{signup&&<div><label className="label">Nama lengkap</label><input className="input" value={name} onChange={e=>setName(e.target.value)} required placeholder="Nama lengkap"/></div>}<div><label className="label">Email</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div><label className="label">Password</label><input className="input" type="password" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} required/></div>{error&&<div className={error.startsWith('Akun dibuat')?'success':'error'}>{error}</div>}<button className="btn primary" disabled={busy}>{busy?'Memproses…':signup?'Buat akun':'Masuk'}</button></form><p className="small muted">Data tersimpan di Supabase dan akses dibatasi oleh Row Level Security.</p></div>
}

function Student({user,profile}){
 const [classes,setClasses]=useState([]),[active,setActive]=useState(null),[entries,setEntries]=useState([]),[tab,setTab]=useState('checkin'),[mood,setMood]=useState(''),[intensity,setIntensity]=useState(3),[note,setNote]=useState(''),[code,setCode]=useState(''),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const {data,error}=await supabase.from('class_students').select('class_id, classes(id,name,join_code,active)').eq('student_id',user.id);if(error){setError(error.message);return}const cs=(data||[]).map(x=>x.classes).filter(Boolean);setClasses(cs);setActive(a=>a||cs[0]||null)}
 async function loadEntries(cid){if(!cid){setEntries([]);return}const {data,error}=await supabase.from('emotion_entries').select('*').eq('student_id',user.id).eq('class_id',cid).order('created_at',{ascending:false});if(error)setError(error.message);else setEntries(data||[])}
 useEffect(()=>{load()},[]);useEffect(()=>{loadEntries(active?.id)},[active?.id]);
 async function join(){setError('');setMsg('');if(!code.trim())return;setBusy(true);const {data,error}=await supabase.rpc('join_class_by_code',{p_join_code:code.trim().toUpperCase()});if(error) setError(error.message); else {setMsg('Berhasil bergabung ke kelas.');setCode('');await load()}setBusy(false)}
 async function checkin(){if(!active)return setError('Gabung kelas terlebih dahulu.');if(!mood)return setError('Pilih emosi terlebih dahulu.');setBusy(true);const {error}=await supabase.from('emotion_entries').insert({student_id:user.id,class_id:active.id,mood_id:mood,intensity,private_note:note.trim()||null});if(error)setError(error.message);else{setMsg('Check-in tersimpan. Jurnal otomatis tersedia di dashboard Guru BK kelas ini.');setMood('');setNote('');await loadEntries(active.id)}setBusy(false)}
 const neg=entries.slice(0,3).filter(x=>NEGATIVE.has(x.mood_id)).length===3&&entries.length>=3;
 return <><Header title={`Halo, ${profile.full_name}`} onLogout={()=>supabase.auth.signOut()}/><div className="content"><div className="actions" style={{justifyContent:'space-between',marginBottom:18}}><div><b>Kelas aktif:</b> {active?.name||'Belum ada kelas'}</div><div className="actions"><input className="input" style={{width:180,margin:0}} placeholder="Kode kelas" value={code} onChange={e=>setCode(e.target.value)}/><button className="btn primary" onClick={join} disabled={busy}>Gabung kelas</button></div></div><div className="nav">{[['checkin','Check-in'],['journal','Jurnal saya'],['history','Riwayat']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>{msg&&<div className="success" style={{marginBottom:12}}>{msg}</div>}{error&&<div className="error" style={{marginBottom:12}}>{error}</div>}{neg&&<div className="alert" style={{marginBottom:12}}>Tiga check-in terakhir menunjukkan emosi yang masuk kategori perlu dipantau. Jika kamu membutuhkan bantuan, kamu bisa menghubungi Guru BK atau orang dewasa yang dipercaya.</div>}{tab==='checkin'&&<div className="grid two"><div className="card"><h2>Bagaimana perasaanmu?</h2><div className="moodgrid">{MOODS.map(m=><button key={m[0]} className={`mood ${mood===m[0]?'selected':''}`} onClick={()=>setMood(m[0])}><div style={{fontSize:28}}>{m[2]}</div><b>{m[1]}</b></button>)}</div><div style={{marginTop:20}}><label className="label">Intensitas: {intensity}/5</label><input style={{width:'100%'}} type="range" min="1" max="5" value={intensity} onChange={e=>setIntensity(+e.target.value)}/></div><div style={{marginTop:18}}><label className="label">Jurnal singkat (opsional)</label><textarea className="input" rows="5" value={note} onChange={e=>setNote(e.target.value)} placeholder="Apa yang ingin kamu ceritakan hari ini?"/></div><button className="btn primary" style={{marginTop:12}} onClick={checkin} disabled={busy}>Simpan check-in</button></div><div className="card soft"><h2>Ruang aman untukmu</h2><p>Check-in bukan diagnosis. Catatanmu dipakai untuk membantu Guru BK memahami pola yang kamu bagikan dan menentukan tindak lanjut yang sesuai.</p><p className="small muted">Jurnal yang kamu tulis pada check-in akan masuk otomatis ke Guru BK yang mengelola kelas tersebut, sesuai pengaturan aplikasi ini.</p></div></div>}{tab==='journal'&&<Journal entries={entries}/>} {tab==='history'&&<History entries={entries}/>}</div></>
}
function Journal({entries}){return <div className="grid">{entries.filter(e=>e.private_note).length?<>{entries.filter(e=>e.private_note).map(e=><div className="card" key={e.id}><div className="actions" style={{justifyContent:'space-between'}}><b>{moodEmoji(e.mood_id)} {moodLabel(e.mood_id)}</b><span className="small muted">{new Date(e.created_at).toLocaleString('id-ID')}</span></div><p style={{whiteSpace:'pre-wrap'}}>{e.private_note}</p><span className="pill">Intensitas {e.intensity}/5</span></div>)}</>:<div className="card soft">Belum ada jurnal.</div>}</div>}
function History({entries}){return <div className="card"><h2>Riwayat check-in</h2><div className="tablewrap"><table className="table"><thead><tr><th>Waktu</th><th>Emosi</th><th>Intensitas</th><th>Jurnal</th></tr></thead><tbody>{entries.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString('id-ID')}</td><td>{moodEmoji(e.mood_id)} {moodLabel(e.mood_id)}</td><td>{e.intensity}/5</td><td>{e.private_note||'—'}</td></tr>)}</tbody></table></div></div>}

function Teacher({user,profile}){
 const [classes,setClasses]=useState([]),[cls,setCls]=useState(null),[students,setStudents]=useState([]),[entries,setEntries]=useState([]),[followups,setFollowups]=useState([]),[tab,setTab]=useState('overview'),[newClass,setNewClass]=useState(''),[journal,setJournal]=useState(null),[error,setError]=useState(''),[msg,setMsg]=useState('');
 async function loadClasses(){const {data,error}=await supabase.from('classes').select('*').eq('teacher_id',user.id).order('created_at');if(error)setError(error.message);else{setClasses(data||[]);setCls(c=>c||(data||[])[0]||null)}}
 async function loadData(cid){if(!cid)return;setError('');const [{data:s,error:se},{data:e,error:ee},{data:f,error:fe}]=await Promise.all([supabase.from('class_students').select('student_id,profiles(id,full_name)').eq('class_id',cid),supabase.from('emotion_entries').select('id,student_id,mood_id,intensity,private_note,created_at,profiles(full_name)').eq('class_id',cid).order('created_at',{ascending:false}),supabase.from('bk_followups').select('*').eq('class_id',cid).order('updated_at',{ascending:false})]);if(se||ee||fe)setError((se||ee||fe).message);setStudents((s||[]).map(x=>({id:x.student_id,name:x.profiles?.full_name||'Siswa'})));setEntries(e||[]);setFollowups(f||[])}
 useEffect(()=>{loadClasses()},[]);useEffect(()=>{loadData(cls?.id)},[cls?.id]);
 async function createClass(){setMsg('');if(!newClass.trim())return;const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data,error}=await supabase.from('classes').insert({teacher_id:user.id,name:newClass.trim(),join_code:code}).select().single();if(error)setError(error.message);else{setNewClass('');setMsg(`Kelas dibuat. Kode bergabung: ${data.join_code}`);await loadClasses();setCls(data)}}
 async function saveFollowup(studentId){const old=followups.find(f=>f.student_id===studentId);const status=old?.status||'baru';const {error}=await supabase.from('bk_followups').upsert({id:old?.id,student_id:studentId,class_id:cls.id,teacher_id:user.id,status,service_type:old?.service_type||'Pemantauan',followup_note:old?.followup_note||'',followup_at:old?.followup_at||new Date().toISOString()},{onConflict:'id'});if(error)setError(error.message);else{setMsg('Tindak lanjut tersimpan.');loadData(cls.id)}}
 const summaries=useMemo(()=>students.map(s=>{const es=entries.filter(e=>e.student_id===s.id);const counts=Object.fromEntries(MOODS.map(m=>[m[0],es.filter(e=>e.mood_id===m[0]).length]));const flag=es.length>=3&&es.slice(0,3).every(e=>NEGATIVE.has(e.mood_id));return {...s,entries:es,total:es.length,counts,last:es[0],flag}},[students,entries]);
 const total=entries.length, negative=entries.filter(e=>NEGATIVE.has(e.mood_id)).length;
 function exportData(){csvDownload(summaries.map(s=>({'Nama Siswa':s.name,'Total Check-in':s.total,'Senang':s.counts.happy,'Tenang':s.counts.calm,'Semangat':s.counts.excited,'Sedih':s.counts.sad,'Cemas':s.counts.anxious,'Marah':s.counts.angry,'Check-in Terakhir':s.last?new Date(s.last.created_at).toLocaleString('id-ID'):'','Indikator 3 Terakhir Negatif':s.flag?'Ya':'Tidak'})),`EmoTrack_${cls.name.replace(/\s+/g,'_')}_ringkasan.csv`);csvDownload(entries.map(e=>({'Nama Siswa':e.profiles?.full_name||'','Waktu':new Date(e.created_at).toLocaleString('id-ID'),'Emosi':moodLabel(e.mood_id),'Intensitas':e.intensity,'Jurnal':e.private_note||''})),`EmoTrack_${cls.name.replace(/\s+/g,'_')}_jurnal.csv`)}
 return <><Header title={`Guru BK · ${profile.full_name}`} onLogout={()=>supabase.auth.signOut()}/><div className="content"><div className="card soft" style={{marginBottom:18}}><div className="actions"><input className="input" style={{margin:0,flex:1}} placeholder="Nama kelas baru" value={newClass} onChange={e=>setNewClass(e.target.value)}/><button className="btn primary" onClick={createClass}>Buat kelas</button><button className="btn secondary" onClick={exportData} disabled={!cls}>Export CSV</button></div><div style={{marginTop:12}}><select className="input" value={cls?.id||''} onChange={e=>setCls(classes.find(c=>c.id===e.target.value))}>{classes.length?classes.map(c=><option key={c.id} value={c.id}>{c.name} · kode {c.join_code}</option>):<option value="">Belum ada kelas</option>}</select></div></div>{msg&&<div className="success" style={{marginBottom:12}}>{msg}</div>}{error&&<div className="error" style={{marginBottom:12}}>{error}</div>}<div className="nav">{[['overview','Ringkasan'],['students','Siswa'],['journals','Jurnal'],['followup','Tindak lanjut']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>{tab==='overview'&&<div className="grid three"><Stat title="Siswa" value={students.length}/><Stat title="Total check-in" value={total}/><Stat title="Check-in emosi negatif" value={negative}/></div>}{tab==='overview'&&<div className="card" style={{marginTop:18}}><h2>Pola emosi kelas</h2>{MOODS.map(m=>{const n=entries.filter(e=>e.mood_id===m[0]).length;return <div key={m[0]} style={{margin:'13px 0'}}><div className="actions" style={{justifyContent:'space-between'}}><span>{m[2]} {m[1]}</span><b>{n}</b></div><div className="bar"><i style={{width:`${total?Math.round(n/total*100):0}%`}}/></div>})}</div>}{tab==='students'&&<StudentTable summaries={summaries} onJournal={s=>setJournal(s)}/>} {tab==='journals'&&<JournalTable entries={entries} onOpen={setJournal}/>} {tab==='followup'&&<FollowupTable summaries={summaries} followups={followups} onSave={saveFollowup}/>}</div>{journal&&<div className="modal" onClick={()=>setJournal(null)}><div className="card" onClick={e=>e.stopPropagation()}><div className="actions" style={{justifyContent:'space-between'}}><h2>Catatan · {journal.name||journal.profiles?.full_name}</h2><button className="btn secondary" onClick={()=>setJournal(null)}>Tutup</button></div>{(journal.entries||[journal]).filter(e=>e.private_note).map(e=><div className="card soft" key={e.id}><b>{moodEmoji(e.mood_id)} {moodLabel(e.mood_id)} · {e.intensity}/5</b><div className="small muted">{new Date(e.created_at).toLocaleString('id-ID')}</div><p style={{whiteSpace:'pre-wrap'}}>{e.private_note}</p></div>)}{!(journal.entries||[journal]).some(e=>e.private_note)&&<p className="muted">Belum ada jurnal.</p>}</div></div>}</>
}
function StudentTable({summaries,onJournal}){return <div className="card"><h2>Daftar siswa</h2><div className="tablewrap"><table className="table"><thead><tr><th>Siswa</th><th>Check-in</th><th>Terakhir</th><th>Indikator</th><th/></tr></thead><tbody>{summaries.map(s=><tr key={s.id}><td><b>{s.name}</b></td><td>{s.total}</td><td>{s.last?`${moodEmoji(s.last.mood_id)} ${moodLabel(s.last.mood_id)} · ${s.last.intensity}/5`:'—'}</td><td>{s.flag?<span className="pill">Pantau</span>:<span className="pill">—</span>}</td><td><button className="btn secondary" onClick={()=>onJournal(s)}>Jurnal</button></td></tr>)}</tbody></table></div></div>}
function JournalTable({entries,onOpen}){return <div className="card"><h2>Jurnal siswa</h2><div className="tablewrap"><table className="table"><thead><tr><th>Waktu</th><th>Siswa</th><th>Emosi</th><th>Jurnal</th></tr></thead><tbody>{entries.filter(e=>e.private_note).map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString('id-ID')}</td><td>{e.profiles?.full_name}</td><td>{moodEmoji(e.mood_id)} {moodLabel(e.mood_id)}</td><td>{e.private_note}</td></tr>)}</tbody></table></div></div>}
function FollowupTable({summaries,followups,onSave}){return <div className="card"><h2>Tindak lanjut</h2>{summaries.map(s=>{const f=followups.find(x=>x.student_id===s.id)||{};return <div className="card soft" style={{marginTop:12}} key={s.id}><div className="actions" style={{justifyContent:'space-between'}}><b>{s.name}</b><select className="input" style={{width:150,margin:0}} value={f.status||'baru'} onChange={e=>f.status=e.target.value}><option>baru</option><option>dipantau</option><option>dihubungi</option><option>selesai</option></select></div><textarea className="input" rows="2" defaultValue={f.followup_note||''} placeholder="Catatan tindak lanjut" onChange={e=>f.followup_note=e.target.value}/><button className="btn primary" style={{marginTop:8}} onClick={()=>onSave(s.id)}>Simpan tindak lanjut</button></div>})}{!summaries.length&&<p className="muted">Belum ada siswa di kelas.</p>}</div>}
function Stat({title,value}){return <div className="card soft"><div className="muted small">{title}</div><div className="stat">{value}</div></div>}
function Header({title,onLogout}){return <div className="top"><div><div className="brand">EmoTrack <span style={{fontWeight:500}}>AutoBK</span></div><div className="small muted">{title}</div></div><button className="btn secondary" onClick={onLogout}>Keluar</button></div>}

export default function App(){const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true);async function load(){const {data}=await supabase.auth.getSession();setSession(data.session);if(data.session){const {data:p}=await supabase.from('profiles').select('*').eq('id',data.session.user.id).single();setProfile(p)}}useEffect(()=>{if(!supabase){setLoading(false);return}load();const {data:l}=supabase.auth.onAuthStateChange(()=>load());setLoading(false);return()=>l.subscription.unsubscribe()},[]);if(!supabase||loading)return <div className="app"><style>{css}</style><Auth onAuth={load}/></div>;return <div className="app"><style>{css}</style><div className="shell">{!session||!profile?<Auth onAuth={load}/>:profile.role==='teacher'?<Teacher user={session.user} profile={profile}/>:<Student user={session.user} profile={profile}/>}</div></div>}
